micronaut:
  application.name: rawdata-converter-app-kag
  server.port: 28086

endpoints:
  prometheus:
    sensitive: false

oauth:
  server-url: https://keycloak.staging-bip-app.ssb.no/auth/realms/ssb/protocol/openid-connect

rawdata.client:
  provider: gcs
  local-temp-folder: temp
  avro-file:
    max.seconds: 3600
    max.bytes: 10485760
    sync.interval: 500000
  gcs:
    bucket-name: ssb-rawdata-dev
    listing.min-interval-seconds: 15
    credential-provider: service-account
    service-account.key-file: ../localenv/auth/gcs/dev-sirius/gcs_credentials.json

rawdata.encryption:
    key: SECURE_KMS_TOKEN
    salt: SALT

rawdata.converter:
  active-by-default: true
  dryrun: false
  storage-type: gcs
  storage-root: gs://ssb-rawdata-dev/datastore
  storage-path: /kilde/karakterer/raadata/v1
  storage-version: 1598553650000
  service-account-key-file: ../localenv/auth/gcs/dev-sirius/gcs_credentials.json
  topic: kag-karakter-test
  window-max-records: 1000
  window-max-time-in-seconds: 60
  initial-position: FIRST
  dataset-meta:
    valuation: INTERNAL
    type: UNBOUNDED
    should-publish-meta: false
    data-access-service:
      host: localhost
      port: 4242
    metadata-distributor-service:
      host: localhost
      port: 2424
      project-id: local
      topic: metadata-distributor-dataset-updates #FIXME
  pseudo: # TODO: Remove
    secrets:
      repo:
        secret1:
          content: C5sn7B4YtwcilAwuVx6NuAsMWLusOSA/ldia40ZugDI=
          type: AES256
    config:
      debug: true
      rules:
        hendelse:
          pattern: '**/hendelse/identifikator'
          func: fpe-fnr(secret1)

